"""
분석 결과를 바탕으로 최적화 Dockerfile 생성.

전략:
  1. Patch가 있는 Finding은 해당 줄을 직접 교체 (line-based patch).
  2. Patch 없는 Finding의 경우 inline 주석으로 권고 사항을 삽입.
  3. SINGLE_STAGE_BUILD Finding은 파일 하단에 multi-stage 템플릿 추가.
"""
from __future__ import annotations

from imgadvisor.models import DockerfileIR, Finding, Severity

_HEADER = """\
# ============================================================
# Generated by imgadvisor — pre-build optimization advisor
# https://github.com/your-org/imgadvisor
#
# 주의: 자동 생성 파일입니다. 실제 배포 전 반드시 검토하세요.
# ============================================================
"""


def recommend(ir: DockerfileIR, findings: list[Finding]) -> str:
    lines = list(ir.raw_lines)

    # 패치 적용 (줄 번호 내림차순 — offset drift 방지)
    patches = [f.patch for f in findings if f.patch is not None]
    patches.sort(key=lambda p: p.line_no, reverse=True)

    for patch in patches:
        idx = patch.line_no - 1
        if 0 <= idx < len(lines) and lines[idx] == patch.old_text:
            lines[idx] = patch.new_text

    # 패치 없는 Finding에 주석 삽입
    _insert_comments(lines, findings)

    body = "\n".join(lines)

    # Multi-stage 템플릿 추가
    multi_finding = next(
        (f for f in findings if f.rule_id == "SINGLE_STAGE_BUILD"), None
    )
    suffix = ""
    if multi_finding:
        suffix = "\n\n" + _format_multistage_block(multi_finding)

    return _HEADER + "\n" + body + suffix


def _insert_comments(lines: list[str], findings: list[Finding]) -> None:
    """Patch 없는 Finding에 # [imgadvisor] 주석을 해당 줄 위에 삽입."""
    # 삽입 위치를 내림차순으로 처리 (offset drift 방지)
    no_patch = [
        f for f in findings
        if f.patch is None and f.line_no is not None and f.rule_id != "SINGLE_STAGE_BUILD"
    ]
    no_patch.sort(key=lambda f: f.line_no or 0, reverse=True)

    for f in no_patch:
        idx = (f.line_no or 1) - 1
        if not (0 <= idx < len(lines)):
            continue
        severity_tag = "FAIL" if f.severity == Severity.HIGH else "WARN"
        comment_lines = [
            f"# [imgadvisor:{severity_tag}] {f.rule_id}",
            f"#   {f.description}",
        ]
        for rec_line in f.recommendation.splitlines()[:3]:
            comment_lines.append(f"#   {rec_line}")
        lines[idx:idx] = comment_lines


def _format_multistage_block(finding: Finding) -> str:
    lines = [
        "# ============================================================",
        "# [imgadvisor] Multi-stage 전환 제안",
        "# 아래 템플릿을 참고해 Dockerfile을 재작성하세요.",
        "# ============================================================",
        "#",
    ]
    for line in finding.recommendation.splitlines():
        lines.append(f"# {line}")
    return "\n".join(lines) + "\n"
